name: shopping_bud
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker:  ^0.6.0+3
  flutter_range_slider: ^1.4.0
  google_fonts: ^0.3.9
  passwordfield: ^0.0.5
  http: any
  progress_dialog: ^1.2.2
  url_launcher: ^5.4.1
  mime: ^0.9.6+3
  toast: ^0.1.5
  shared_preferences: "^0.4.1"
  firebase_auth: ^0.11.1+8
  google_sign_in: ^4.0.4
  flutter_facebook_login: ^2.0.1
  multi_image_picker:
  flutter_tindercard: ^0.1.8
  async: ^2.4.0
  path_provider:
  intl: ^0.16.1
  date_format: ^1.0.8
  jiffy: ^3.0.1
  servicestack: ^1.0.11
  async_loader: ^0.1.2
  firebase_messaging: ^5.0.2
  video_player: ^0.10.8+1
  file_picker:
  permission_handler: ^4.0.0
  flutter_downloader:
  audioplayer:
  photo_view: ^0.5.0
  flutter_uploader:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/add.png
    - images/addUser.png
    - images/twitter.png
    - images/googlePlus.png
    - images/facebook.png
    - images/forgot.png
    - images/add.png
    - images/login.png
    - images/signup.png
    - images/smartphone.png
    - images/woman.png
    - images/woman1.jpg
    - images/woman2.jpg
    - images/male.png
    - images/whiteTick.png
    - images/addprofile.png
    - images/Group64.png
    - images/home.png
    - images/speech-bubble.png
    - images/user.png
    - images/setting.png
    - images/right.png
    - images/userPink.png
    - images/user1.png
    - images/lock.png
    - images/exit.png
    - images/question.png
    - images/term.png
    - images/delete-friend.png
    - images/matches4-contacts.png
    - images/man1.jpg
    - images/videocall.png
    - images/cancel.png
    - images/heart.png
    - images/chat-bubble.png
    - images/setting.png
    - images/settings.png
    - images/bell.png
    - images/thumb.png
    - images/followerpink.png
    - images/chat.png
    - images/happy.png
    - images/notification.png
    - images/logo.png
    - images/edit.png
    - images/Logoshop.png
    - images/back.jpeg
    - images/pp.jpg
    - images/eye.png
    - images/follower_white.png
    - images/like_white.png
    - images/agreement.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf

    - family: Mistral
      fonts:
        - asset: fonts/Mistral.ttf

